# picom config

# backend
backend = "xrender";

# opacity
inactive-opacity = 0.9;
active-opacity = 1.0;
frame-opacity = 1.0;

# fading
fading = true;
fade-in-step = 0.07;
fade-out-step = 0.07;

# shadows
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.6;
shadow-exclude = [
    "name = 'Notification'",
    "class_g = 'i3-frame'",
    "class_g = 'Dunst'",
    "_GTK_FRAME_EXTENTS@:c"
];

# no tearing
vsync = true;

# window type rules
wintypes:
{
    tooltip = { fade = true; shadow = true; opacity = 0.9; };
    dock = { shadow = false; };
    dnd = { shadow = false; };
};
